sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mgmchan1216/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true mgmchan1216/react-test npm test

after_success:
  - docker build -t mgmchan1216/multi-client ./client
  - docker build -t mgmchan1216/multi-server ./server
  - docker build -t mgmchan1216/multi-nginx ./nginx
  - docker build -t mgmchan1216/multi-worker ./worker

  # push out these built images to DockerHub instead of
  # asking ElasticBeanstalk to build

  # login to docker CLI using Travis environment variables
  - echo "$DOCKER_PSWD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images off 
  - docker push mgmchan1216/multi-client
  - docker push mgmchan1216/multi-nginx
  - docker push mgmchan1216/multi-server
  - docker push mgmchan1216/multi-worker

deploy:
	provider: elasticbeanstalk
	region: ap-southeast-1
	app: Multi-docker
	env: MultiDocker-env
	bucket_name: elasticbeanstalk-ap-southeast-1-003053758680
	bucket_path: docker-multi
	on:
		branch: master
	access_key_id: $AWS_ACCESS_KEY
	secret_access_key: $AWS_SECRET_KEY 
